import {
  Accessibility,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  Beer,
  Bell,
  Bike,
  CalendarCheck,
  CalendarPlus,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  Clock,
  Coffee,
  Compass,
  Dice5,
  Download,
  Dumbbell,
  Eye,
  EyeOff,
  FerrisWheel,
  Film,
  Flame,
  Footprints,
  Gamepad2,
  Hand,
  Heart,
  Info,
  Languages,
  LocateFixed,
  Lock,
  LogOut,
  type LucideIcon,
  type LucideProps,
  Mail,
  Map as MapIcon,
  MapPin,
  Martini,
  Moon,
  Mountain,
  Music,
  Navigation2,
  Palette,
  PartyPopper,
  Pencil,
  Plus,
  Radio,
  ScanFace,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Shuffle,
  Snowflake,
  Sparkle,
  Sparkles,
  Star,
  Sun,
  Thermometer,
  Ticket,
  Timer,
  Trees,
  User,
  Users,
  Utensils,
  Vibrate,
  Volume2,
  Waves,
  WifiOff,
  Wine,
  X,
} from "lucide-react-native"

import { useScheme } from "./scheme"

// DESIGN.md §9 — kebab names match lucide-react on web
export const ICONS = {
  accessibility: Accessibility,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  ban: Ban,
  beer: Beer,
  bell: Bell,
  bike: Bike,
  "calendar-check": CalendarCheck,
  "calendar-plus": CalendarPlus,
  camera: Camera,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "circle-check": CircleCheck,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  "dice-5": Dice5,
  download: Download,
  dumbbell: Dumbbell,
  eye: Eye,
  "eye-off": EyeOff,
  "ferris-wheel": FerrisWheel,
  film: Film,
  flame: Flame,
  footprints: Footprints,
  "gamepad-2": Gamepad2,
  hand: Hand,
  heart: Heart,
  info: Info,
  languages: Languages,
  "locate-fixed": LocateFixed,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  map: MapIcon,
  "map-pin": MapPin,
  martini: Martini,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  "navigation-2": Navigation2,
  palette: Palette,
  "party-popper": PartyPopper,
  pencil: Pencil,
  plus: Plus,
  radio: Radio,
  "scan-face": ScanFace,
  search: Search,
  send: Send,
  settings: Settings,
  "shield-check": ShieldCheck,
  shuffle: Shuffle,
  snowflake: Snowflake,
  sparkle: Sparkle,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  thermometer: Thermometer,
  ticket: Ticket,
  timer: Timer,
  trees: Trees,
  user: User,
  users: Users,
  utensils: Utensils,
  vibrate: Vibrate,
  "volume-2": Volume2,
  waves: Waves,
  "wifi-off": WifiOff,
  wine: Wine,
  x: X,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

type Props = Omit<LucideProps, "ref"> & { name: IconName }

export const Icon = ({ name, size = 20, strokeWidth = 1.5, color, ...rest }: Props) => {
  const { c } = useScheme()
  const Glyph = ICONS[name]
  return <Glyph size={size} strokeWidth={strokeWidth} color={color ?? c.fg1} {...rest} />
}
