import type { Venue } from "@justmate/protocol"

// the hand-tagged Kraków list that drizzle/0006_venues.sql and 0008 seed; tests and the mock run on it
export const KRAKOW_VENUES: Venue[] = [
  {
    id: "dvor",
    name: "Vinotéka Dvor",
    kind: "wine_bar",
    rating: 4.7,
    opens: "16:00",
    closes: "23:00",
    lat: 50.059,
    lng: 19.939,
    modes: ["date"],
    fits: ["wine", "dinner", "late bar", "cocktails"],
  },
  {
    id: "nook",
    name: "Kafé Nook",
    kind: "cafe",
    rating: 4.6,
    opens: "08:00",
    closes: "20:00",
    lat: 50.064,
    lng: 19.933,
    modes: ["date", "mate"],
    fits: ["coffee", "brunch", "tea", "dessert", "lunch"],
  },
  {
    id: "meeple",
    name: "Meeple Café",
    kind: "board_game_cafe",
    rating: 4.8,
    opens: "12:00",
    closes: "00:00",
    lat: 50.057,
    lng: 19.944,
    modes: ["mate"],
    fits: ["board games", "cards", "chess", "coffee", "beer"],
  },
  {
    id: "tap",
    name: "Tap Room 9",
    kind: "beer_bar",
    rating: 4.5,
    opens: "15:00",
    closes: "01:00",
    lat: 50.062,
    lng: 19.941,
    modes: ["mate"],
    fits: ["beer", "pub quiz", "darts", "pool"],
  },
  {
    id: "lumen",
    name: "Kino Lumen",
    kind: "cinema",
    rating: 4.7,
    opens: "12:00",
    closes: "23:30",
    lat: 50.065,
    lng: 19.926,
    modes: ["date", "mate"],
    fits: ["cinema", "comedy night", "comedy"],
  },
  {
    id: "boulder",
    name: "Boulder Hall Nord",
    kind: "climbing_gym",
    rating: 4.6,
    opens: "07:00",
    closes: "22:00",
    lat: 50.079,
    lng: 19.935,
    modes: ["mate"],
    fits: ["climbing", "gym", "yoga"],
  },
  {
    id: "steps",
    name: "River steps",
    kind: "riverside",
    rating: null,
    opens: null,
    closes: null,
    lat: 50.051,
    lng: 19.936,
    modes: ["date", "mate"],
    fits: ["walk", "sunset", "picnic", "running", "riverside", "park bench", "cycling"],
  },
  {
    id: "altitude",
    name: "Altitude",
    kind: "rooftop_bar",
    rating: 4.4,
    opens: "17:00",
    closes: "02:00",
    lat: 50.066,
    lng: 19.945,
    modes: ["date"],
    fits: ["cocktails", "rooftop", "wine", "dancing"],
  },
  {
    id: "planty",
    name: "Planty Park",
    kind: "park",
    rating: null,
    opens: null,
    closes: null,
    lat: 50.06,
    lng: 19.933,
    modes: ["date", "mate"],
    fits: ["walk", "picnic", "park bench", "running", "frisbee"],
  },
  {
    id: "blonia",
    name: "Błonia Meadow",
    kind: "park",
    rating: null,
    opens: null,
    closes: null,
    lat: 50.06,
    lng: 19.91,
    modes: ["date", "mate"],
    fits: ["running", "frisbee", "football", "picnic", "cycling", "walk", "stargazing"],
  },
  {
    id: "strike",
    name: "Strike Lanes",
    kind: "bowling",
    rating: 4.3,
    opens: "12:00",
    closes: "00:00",
    lat: 50.069,
    lng: 19.915,
    modes: ["date", "mate"],
    fits: ["bowling", "arcade", "pool", "darts", "video games"],
  },
  {
    id: "noodle",
    name: "Noodle Corner",
    kind: "restaurant",
    rating: 4.6,
    opens: "12:00",
    closes: "22:00",
    lat: 50.05,
    lng: 19.945,
    modes: ["date", "mate"],
    fits: ["ramen", "street food", "lunch", "dinner", "pizza"],
  },
  {
    id: "cellar",
    name: "Blue Cellar",
    kind: "jazz_club",
    rating: 4.7,
    opens: "19:00",
    closes: "02:00",
    lat: 50.0615,
    lng: 19.9375,
    modes: ["date", "mate"],
    fits: ["jazz club", "jazz bar", "live gig", "gig", "open mic", "jam session", "concert"],
  },
  {
    id: "arsenal",
    name: "Arsenal Gallery",
    kind: "museum",
    rating: 4.5,
    opens: "10:00",
    closes: "18:00",
    lat: 50.0645,
    lng: 19.9405,
    modes: ["date", "mate"],
    fits: ["exhibition", "museum", "street art", "workshop", "talk"],
  },
  {
    id: "corner",
    name: "Corner Café",
    kind: "cafe",
    rating: 4.5,
    opens: "08:00",
    closes: "21:00",
    lat: 50.0675,
    lng: 19.9125,
    modes: ["date", "mate"],
    fits: ["coffee", "tea", "brunch", "dessert", "board games", "chess"],
  },
  {
    id: "court",
    name: "Court Club",
    kind: "sports_centre",
    rating: 4.5,
    opens: "07:00",
    closes: "23:00",
    lat: 50.071,
    lng: 19.925,
    modes: ["mate"],
    fits: ["padel", "tennis", "basketball", "gym"],
  },
  {
    id: "flow",
    name: "Flow Studio",
    kind: "sports_centre",
    rating: 4.8,
    opens: "07:00",
    closes: "21:00",
    lat: 50.057,
    lng: 19.945,
    modes: ["date", "mate"],
    fits: ["yoga", "gym"],
  },
  {
    id: "lido",
    name: "Lido Pool",
    kind: "pool",
    rating: 4.4,
    opens: "06:00",
    closes: "22:00",
    lat: 50.054,
    lng: 19.928,
    modes: ["mate"],
    fits: ["swim"],
  },
]
